// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA80S0ZGaSXiinZKsbdUBiemf58y3aMhE4',
    appId: '1:555032934418:web:0681076d5b05407c89c0cb',
    messagingSenderId: '555032934418',
    projectId: 'kabaadi-wala-edefc',
    authDomain: 'kabaadi-wala-edefc.firebaseapp.com',
    storageBucket: 'kabaadi-wala-edefc.firebasestorage.app',
    measurementId: 'G-6NMR4GRD3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbT-nxvsK2hs188ujIxID116i2Tyk4-HY',
    appId: '1:555032934418:android:0d694e8d49e9a0aa89c0cb',
    messagingSenderId: '555032934418',
    projectId: 'kabaadi-wala-edefc',
    storageBucket: 'kabaadi-wala-edefc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_eSm0PVCmj-541cmSROoELtMfYZkW-Zw',
    appId: '1:555032934418:ios:e736f054f19f8a1689c0cb',
    messagingSenderId: '555032934418',
    projectId: 'kabaadi-wala-edefc',
    storageBucket: 'kabaadi-wala-edefc.firebasestorage.app',
    iosBundleId: 'com.example.kabaadiWala',
  );
}
